/**:
  ros__parameters:
    approximate_sync: True  # Whether to use approximate synchronization of topics. Set to true if the left and right cameras do not produce exactly synced timestamps
    use_system_default_qos: False  # Use the RMW QoS settings for the image and camera info subscriptions.
    queue_size: 5

    # disparity
    stereo_algorithm: 0  # Stereo algorithm: Block Matching (0) or Semi-Global Block Matching (1)
    prefilter_size: 9  # Normalization window size in pixels (must be odd)
    prefilter_cap: 31  # Bound on normalized pixel values
    correlation_window_size: 15  # SAD correlation window width in pixels (must be odd)
    min_disparity: 0  # Disparity to begin search at in pixels
    disparity_range: 64  # Number of disparities to search in pixels (must be a multiple of 16)
    texture_threshold: 10  # Filter out if SAD window response does not exceed texture threshold
    speckle_size: 100  # Reject regions smaller than this size in pixels
    speckle_range: 4  # Maximum allowed difference between detected disparities
    disp12_max_diff: 0  # Maximum allowed difference in the left-right disparity check in pixels (Semi-Global Block Matching only)
    uniqueness_ratio: 15.0  # Filter out if best match does not sufficiently exceed the next-best match
    P1: 200.0  # The first parameter controlling the disparity smoothness (Semi-Global Block Matching only)
    P2: 400.0  # The second parameter ccontrolling the disparity smoothness  (Semi-Global Block Matching only)
    full_dp: False  # Run the full variant of the algorithm (Semi-Global Block Matching only)

    # pointcloud
    use_color: True  # Generate point cloud with rgb data.
    avoid_point_cloud_padding: False  # Avoid alignment padding in the generated point cloud. This reduces bandwidth requirements, as the point cloud size is halved. Using point clouds without alignment padding might degrade performance for some algorithms.