image_width: 1920
image_height: 1080
camera_name: camera0
camera_matrix:
  rows: 3
  cols: 3
  data: [6969.61263,    0.     ,  975.66294,
            0.     , 6236.51694,  564.36173,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-1.808247, -65.881007, -0.029502, 0.014618, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [6460.70264,    0.     ,  988.32353,    0.     ,
            0.     , 6120.91016,  560.50044,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]